# Generated by Django 4.1.7 on 2023-03-01 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbp_rate', models.CharField(max_length=200)),
                ('smtp_user', models.CharField(max_length=200)),
                ('smtp_server', models.CharField(max_length=200)),
                ('smtp_port', models.CharField(max_length=200)),
                ('smtp_pass', models.CharField(max_length=200)),
                ('smtp_sender', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('cc_email_id', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('vat_type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('invoice_file_name', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=200)),
                ('previous_month', models.CharField(max_length=200)),
                ('previous_year', models.CharField(max_length=200)),
                ('current_year', models.CharField(max_length=200)),
                ('total_cost', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('invoice_Type', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child_Comp', models.CharField(max_length=200)),
                ('Parent_Comp', models.CharField(max_length=200)),
                ('Parent_Company_Name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CpDeskInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('invoice_file_pdf', models.CharField(max_length=200)),
                ('invoice_file_excel', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=200)),
                ('previous_month', models.CharField(max_length=200)),
                ('previous_year', models.CharField(max_length=200)),
                ('current_year', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('is_considered', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
